### ISSUE TITLE
Verification fails with latest versions of ring/compojure/anti-forgery

### ISSUE THREAD

**Issue by sventech** [ring-clojure/ring-anti-forgery#10]
I've got a [StackOverflow question here](http://stackoverflow.com/questions/30172569/clojure-anti-forgery-csrf-token-invalid-with-latest-version-ring-compojure) and [minimal code and usage example here](https://github.com/sventech/CSRF). I hope I'm missing something, but it appears to fail where it should succeed.

Basically I use `cURL` to get the anti-forgery token (using the session cookies feature to maintain my session) and then `POST` form data manually inserting the `X-CSRF-Token` header.

**Comment by weavejester** [comment]
Your problem is that you're applying the anti-forgery middleware twice: once in your code, and once via ring-defaults. This results in a situation where your handler sees the inner CSRF token, but it's the outer CSRF token that's written to the session.

**Comment by sventech** [comment]
Thanks! It would be a good idea to document that the CSRF token is added by `wrap-defaults`. The README implies that CSRF will only be set if you set `:anti-forgery true`. I'd be happy to create a pull request if you  have some idea where it should go.

**Comment by weavejester** [comment]
We could add a section to the Ring-Defaults README that details the different option maps available.

**Comment by sventech** [comment]
I've added [an issue on `ring-defaults`](https://github.com/ring-clojure/ring-defaults/issues/14) to keep track of it.
