### ISSUE TITLE
New release with OPTIONS support

### ISSUE THREAD

**Issue by msassak** [ring-clojure/ring-anti-forgery#11]
Are there plans for making a new release of ring-anti-forgery soon now that https://github.com/ring-clojure/ring-anti-forgery/pull/8 has been merged? I need that commit for a project I'm working on, and it'd be great to require 1.0.1 rather than building my own fork. Thanks!

**Comment by weavejester** [comment]
Yes, sorry. This was an oversight. I'll release 1.0.1 tomorrow.

**Comment by weavejester** [comment]
Done.

**Comment by msassak** [comment]
Thanks for the quick response!
