### ISSUE TITLE
When does the token change, exactly?  How to accommodate changes in persistent session, if at all?

### ISSUE THREAD

**Issue by limist** [ring-clojure/ring-anti-forgery#13]
Sorry if this is blindingly obvious, but...Does the anti-forgery token change whenever the web server process changes, i.e. after a restart? If so, and if we're using some kind of persistent sessions backend, should we 1) not store the anti-forgery token in a persistent session at all; 2) or if it should be stored, how should the stored token be updated? (from the optional custom error handler, or...?)  Thanks in advance for any help.

**Comment by weavejester** [comment]
The anti-forgery token is unique to the session, and remains the same for the duration of the session. When the session ends, that's when the token changes. It's unrelated to the server process.

**Comment by limist** [comment]
Meaning it's tied to the session id? I'm seeing 403 errors when I use an older/extant session id (that's still unexpired), that reads/looks-up a prior session from a persistent session store (which stores the anti-forgery token). Should the session store not include the anti-forgery token at all?  Thanks!

**Comment by weavejester** [comment]
Could you give a little more detail about the error you're seeing?

If you have a persistent session store, restarting the server should have no effect on the anti-forgery middleware.

**Comment by limist** [comment]
Sure, in my local development environment, upon sending an xhr POST from a ClojureScript client to a Ring backend, I get a 403 error, invalid CSRF token.  The CSRF token was embedded in the sending page as a JS var, and it does not match the CSRF token that was read from the persistent session.

Since the cookie and associated persistent session are fairly old (20-30 days), and the Ring backend process restarted many times in that period, I had guessed that somehow, the ring-anti-forgery issued a new token.  Yet that doesn't match my mental model that the persistent session and its associated CSRF token would be looked up on the request, and the old/persistent CSRF passed back on the response, as usual.  So there's likely a wrong assumption in there somewhere...

**Comment by weavejester** [comment]
The token is calculated as:

```clojure
(or (get-in request [:session ::anti-forgery-token])
    (random/base64 60))
```

The token isn't removed from the session by the middleware, so something else must be resetting the session.

**Comment by limist** [comment]
Ah, that's very helpful to understand things, I will investigate further. Thanks!

**Comment by limist** [comment]
Fixed this; the problem arose when trying to post on an expired (idle-timeout) session.  Thanks a lot for the explanations and clarifications above!
