### ISSUE TITLE
Need disable-flag for test

### ISSUE THREAD

**Issue by ayato0211** [ring-clojure/ring-anti-forgery#9]
I really want to need it or something like that.
Maybe we can create some test code more easily when create some applications if existed that I think.

Rails provided.
http://guides.rubyonrails.org/configuring.html
`config.action_controller.allow_forgery_protection`

Thanks.

**Comment by weavejester** [comment]
You don't need a flag; just don't include the middleware when running tests.

**Comment by ayato0211** [comment]
Thank you for your reply, that make sense. But in my situation couldn't that.
Just because I'm using `lib-noir` and `noir.util.middleware/app-handler`, you know that library included this library and using `anti-forgery` middleware implicitly.

My situation is like this

```
;; src/something/handler.clj
(ns something.handler
  (:require ...
            [noir.util.middleware :as noir-middleware]
                ...))

(def app
  (noir-middleware/app-handler
   [any-routes
    app-routes]))
```

```
;; test/something/test/handler.clj
(ns something.test.handler
  (:require [clojure.test :refer :all]
            [something.handler :refer :all]
            [ring.mock.request :refer :all]))

;; I want to use `app` same as application, like this.
;; However, unfortunately we can see "invalid anti-forgery token" error in this situation
;;(app (request :post "/any" {:foo "foo"}))
```

So what should I do?
I think this problem from this library...

Thanks

**Comment by weavejester** [comment]
It looks like the latest version of `app-handler` uses [ring-defaults](https://github.com/ring-clojure/ring-defaults), so you can write:

```clojure
(noir-middleware/app-helper
 [any-routes app-routes]
 :ring-defaults (assoc-in ring-defaults/site-defaults [:security :anti-forgery] false))
```

**Comment by ayato0211** [comment]
I see. Many thanks :)
